### ISSUE TITLE
Installation on Ubuntu ...

### ISSUE THREAD

**Issue by guettli** [autokey-py3/autokey#30]
The current installation instructions are quite complicated for newcomers.

Why not make an deb package to make it available via the Ubuntu Software Center?

**Comment by phd21** [comment]
+1 for this request. Please make an easy to install ".deb" package or provide a PPA. If you already have the original Autokey installed, would installing this overwrite that? How about calling this "autokey2-qt"? I am using Linux Mint KDE 17.3. Thank you.

**Comment by JohnJohnstone** [comment]
Hardly a complicated process. 
@phd21 There is both a GTK and QT GUI available for Autokey, so wouldnt make sense to call it autokey2-qt unless your going to package deb files i would do one for the GTK and QT respectively. 

Should maybe look into creating snap packages, more so if your an Ubuntu user considering they are the company behind snap packages.

**Comment by troxor** [comment]
I'm currently working on this, but don't use Ubuntu as my main distro so it may take a little bit of time to figure out.

**Comment by JohnJohnstone** [comment]
@troxor are you working on ubuntu ppa's or snap packages? I was going try build a snap for the gtk version.

**Comment by troxor** [comment]
@Johnstone-Tech I'm working on a PPA package; there are also AppImage and Flatpak as well, to be less Ubuntu-specific.

**Comment by JohnJohnstone** [comment]
@troxor Snap is available on a few Distributions now,  obviusly being pushed by Canonical as they made it but i feel a lot of other distributions are going to adopt snap packages. Note i am currently using arch Linux to play with snap packages. I will check out the other solutions after ive had a play with snapcraft.

**Comment by probonopd** [comment]
@troxor if you can do a PPA for trusty or earlier, then it would be easy to convert your PPA to an AppImage, essentially giving you the AppImage "for free". Let me know if you are interested in this.

**Comment by troxor** [comment]
Packages have been created and uploaded to my PPA for Xenial (16.04) as a starting point. All willing guinea pigs are welcome to try it out and provide feedback.

Warning: no promises yet on stability/usability!

```
sudo add-apt-repository ppa:troxor/autokey
sudo apt-get update
sudo apt-get install autokey-gtk
```
This should supercede the version provided by default and python3-related dependencies should be pulled in if all went well. I haven't tried out the QT frontend yet.

**Comment by probonopd** [comment]
@troxor thanks a lot but could you also do a PPA for trusty or earlier?

**Comment by troxor** [comment]
@probonopd  I looked into it, but the minimum Python3 version is 3.5 due to the dependency on `typing` module. Consequently, it was easier to just require the latest LTS.

**Comment by Tronic69** [comment]
I hoped it will be working with the PPA, but I got the same error message as using development version from GIT with pip3. 

```
$ > autokey
Traceback (most recent call last):
  File "/usr/bin/autokey", line 9, in <module>
    load_entry_point('autokey==0.93.7', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3/dist-packages/autokey/gtkapp.py", line 30, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 23, in <module>
    from autokey.iomediator import IoMediator
  File "/usr/lib/python3/dist-packages/autokey/iomediator.py", line 41, in <module>
    from .iomediator00 import IoMediator, Waiter, KeyGrabber, Recorder
  File "/usr/lib/python3/dist-packages/autokey/iomediator00.py", line 7, in <module>
    from .interface import XRecordInterface
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 24, in <module>
    import pyatspi
  File "/usr/lib/python3/dist-packages/pyatspi/__init__.py", line 17, in <module>
    require_version('Atspi', '2.0')
NameError: name 'require_version' is not defined
```

I use Linux Mint 18.1 (based on Ubuntu 16.04).

**Comment by xircon** [comment]
What version of python-atspi do you have installed?

**Comment by troxor** [comment]
I tested on a Mint 18.1 VM fresh install, and autokey-gtk launched fine, albeit with an Atspi warning. I'll fix this in the sources shortly.

**Comment by Tronic69** [comment]
@xircon 
This is what is installed:

```
# > dpkg -l *atspi*
+++-================================-=====================-=====================
ii  gir1.2-atspi-2.0                 2.18.3-4ubuntu1       amd64                
ii  libatspi2.0-0:amd64              2.18.3-4ubuntu1       amd64                
ii  python-pyatspi                   2.18.0+dfsg-3         all                  
ii  python-pyatspi2                  2.18.0+dfsg-3         all                  
ii  python3-pyatspi                  2.18.0+dfsg-3         all                  
ii  python3-pyatspi2                 2.18.0+dfsg-3         all                  
```

@troxor 
I'll stay tuned for new version. Will it go into PPA, too?

**Comment by troxor** [comment]
@Tronic69 perhaps try running `debsums` on all packages related to autokey; I aim to maintain the PPA alongside the codebase, periodically issuing new releases there. `git HEAD` will always be the latest code, of course.

**Comment by troxor** [comment]
Marking as closed since PPA is complete. README has been updated as well.

**Comment by Tronic69** [comment]
Still not working here with PPA (get new error messages):
```
$ > autokey
Traceback (most recent call last):
  File "/usr/bin/autokey", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'autokey==0.93.7' distribution was not found and is required by the application
```

This is what I get from debsums:
```
# > debsums python3-pyinotify wmctrl xautomation imagemagick python3-gi gir1.2-gtk-3.0 gir1.2-gtksource-3.0 gir1.2-glib-2.0 gir1.2-notify-0.7 python3-dbus zenity python3-xlib autokey-gtk | awk '$NF !~ /OK/ {print $0}'
/usr/share/applications/display-im6.desktop                               FAILED

# > ls -ld /usr/share/applications/display-im6.desktop-rw-r--r-- 1 root root 998 2017-01-04 19:07 /usr/share/applications/display-im6.desktop

# > dpkg -S /usr/share/applications/display-im6.desktopimagemagick: /usr/share/applications/display-im6.desktop
```

Installation via pip3 is not working anymore and for me it looks like an error in dependencies:
```
# > pip3 install git+https://github.com/autokey-py3/autokey
Collecting git+https://github.com/autokey-py3/autokey
  Cloning https://github.com/autokey-py3/autokey to /tmp/pip-8yvln517-build
            ...
    checking for DBUS... yes
    checking for DBUS_GLIB... no
    configure: error: Package requirements (dbus-glib-1 >= 0.70) were not met:
    
    No package 'dbus-glib-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_GLIB_CFLAGS
    and DBUS_GLIB_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kg8afhgt/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-kg8afhgt/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-kg8afhgt/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-kg8afhgt/dbus-python/build/temp.linux-x86_64-3.5/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kg8afhgt/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o4b2jt_3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-kg8afhgt/dbus-python/
```
But there is no package dbus-glib-1, just packages libdbus-glib-1-2 (maybe because it is deprecated): 
```
# > dpkg -l *dbus-glib-1*
||/ Name                             Version               Architektur          
+++-================================-=====================-=====================
ii  libdbus-glib-1-2:amd64           0.106-1               amd64                
ii  libdbus-glib-1-2:i386            0.106-1               i386                 

# > apt show libdbus-glib-1-2
Package: libdbus-glib-1-2
Version: 0.106-1
Priority: standard
Section: libs
Source: dbus-glib
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 216 kB
Depends: libc6 (>= 2.14), libdbus-1-3 (>= 1.9.14), libglib2.0-0 (>= 2.31.8)
Homepage: http://www.freedesktop.org/wiki/Software/DBusBindings
Task: standard, mythbuntu-frontend, mythbuntu-backend-slave, mythbuntu-backend-master, ubuntu-sdk-libs, ubuntu-touch
Supported: 5y
Download-Size: 67,1 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Description: simple interprocess messaging system (GLib-based shared library)
 D-Bus is a message bus, used for sending messages between applications.
 Conceptually, it fits somewhere in between raw sockets and CORBA in
 terms of complexity.
 .
 This package provides a deprecated GLib-based shared library for
 applications using the GLib interface to D-Bus. New code should use
 GDBus, part of GLib, instead.
```

**Comment by nemonein** [comment]
I tried the ppa, and installed autokey-gtk.

I ran autokey-gtk -c, and I got this message.

> $ autokey-gtk -c
> Traceback (most recent call last):
>   File "/usr/bin/autokey-gtk", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'dbus-python' distribution was not found and is required by autokey

However, dbus-python (python3-dbus) is already installed.

> $ apt policy python3-dbus
> python3-dbus:
>   Installed: 1.2.0-3
>   Candidate: 1.2.0-3
>   Version table:
>  *** 1.2.0-3 500
>         500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
>         100 /var/lib/dpkg/status


Any help to solve this one would be appreciated.
Thanks.

**Comment by troxor** [comment]
A new package has been pushed to the PPA that should fix this. Sorry for the regression! A second PPA (ppa:troxor/autokey-testing) has been created with the aim of keeping the main one stable.

**Comment by nemonein** [comment]
Thanks. The new package works fine on Ubuntu 16.04.

**Comment by Tronic69** [comment]
I still have the same error when try to start autokey as 11 days ago (https://github.com/autokey-py3/autokey/issues/30#issuecomment-270502707):
```
$ > autokey
Traceback (most recent call last):
  File "/usr/bin/autokey", line 9, in <module>
    load_entry_point('autokey==0.93.7', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3/dist-packages/autokey/gtkapp.py", line 30, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 23, in <module>
    from autokey.iomediator import IoMediator
  File "/usr/lib/python3/dist-packages/autokey/iomediator.py", line 41, in <module>
    from .iomediator00 import IoMediator, Waiter, KeyGrabber, Recorder
  File "/usr/lib/python3/dist-packages/autokey/iomediator00.py", line 7, in <module>
    from .interface import XRecordInterface
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 34, in <module>
    import pyatspi
  File "/usr/lib/python3/dist-packages/pyatspi/__init__.py", line 17, in <module>
    require_version('Atspi', '2.0')
NameError: name 'require_version' is not defined
```

And same error try installing it via pip3 as 4 posts above!

**Comment by mamantoha** [comment]
I had similar error:

```
~ autokey-gtk 
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 9, in <module>
    load_entry_point('autokey==0.93.10', 'console_scripts', 'autokey-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3/dist-packages/autokey/gtkapp.py", line 30, in <module>
    from autokey import service, monitor
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 23, in <module>
    from autokey.iomediator import IoMediator
  File "/usr/lib/python3/dist-packages/autokey/iomediator.py", line 41, in <module>
    from .iomediator00 import IoMediator, Waiter, KeyGrabber, Recorder
  File "/usr/lib/python3/dist-packages/autokey/iomediator00.py", line 7, in <module>
    from .interface import XRecordInterface
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 33, in <module>
    gi.require_version('Atspi', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Atspi not available
```

Fixed by installing `python3-pyatspi`
